default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: app409_oauth_development

test:
  <<: *default
  database: app409_oauth_test

production:
  <<: *default
  database: app409_oauth_production
  username: app409_oauth
  password: <%= ENV['APP409_OAUTH_DATABASE_PASSWORD'] %>
